name: FBSTUDIO
channels:
  - defaults
  - conda-forge
dependencies:
  # - python=3.12
  - matplotlib
  - fretbursts
  - Qt.py >= 1.4.1
  - PySide6 >= 6.0
  - NumPy < 2.0.0
  - pip:
    - NodeGraphQt
    - -e .